# -*- coding: utf-8 -*-
"""Q1_(new).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5NN5t3PpsZFqTBn6b70F64tDJQCDbGz

# Q1 – Vision Language Model Attribute Extraction

## Objective

Extract structured attributes from person and garment images using the **MiniCPM-V-2_6-int4 Vision Language Model** and generate validated JSON outputs for all image pairs.

---

## Model

- **Vision Language Model:** MiniCPM-V-2_6-int4
- **Framework:** Hugging Face Transformers
- **GPU:** Tesla T4 (Google Colab)
- **Precision:** 4-bit Quantized Model

---

## Input

- Person Images
- Garment Images

---

## Extracted Attributes

### Person

- Pose Category
- Upper Body Visibility
- Lower Body Visibility

### Garment

- Garment Type
- Sleeve Length
- Neckline
- Primary Color
- Pattern

---

## Processing Pipeline

1. Load person and garment images.
2. Resize images while preserving aspect ratio.
3. Query MiniCPM-V using structured prompts.
4. Parse the model response into JSON.
5. Validate output using a Pydantic schema.
6. Save the final JSON results.

---

## Output

Generated file:

- `output/sample_output_q1.json`

The JSON contains structured annotations for all **5 image pairs**.

---

## Technologies Used

- Python
- PyTorch
- Hugging Face Transformers
- MiniCPM-V-2_6-int4
- Pydantic
- Pillow
- Accelerate
- BitsAndBytes

---

**Author:** Nandana R
"""

from google.colab import drive
drive.mount('/content/drive')

PROJECT_DIR = "/content/drive/MyDrive/XIPL_SDE_Assessment/Q1"

PERSON_DIR = f"{PROJECT_DIR}/person"
GARMENT_DIR = f"{PROJECT_DIR}/garment"
OUTPUT_DIR = f"{PROJECT_DIR}/output"

import os

print(os.listdir(PERSON_DIR))
print(os.listdir(GARMENT_DIR))

import torch
print("Pre-installed torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

!pip uninstall -y transformers tokenizers

!pip install -q \
    "transformers==4.44.2" \
    "tokenizers==0.19.1" \
    "sentencepiece==0.1.99" \
    "accelerate==0.30.1" \
    "bitsandbytes>=0.43.1" \
    pydantic

import os
from google.colab import drive

drive.mount('/content/drive')

PROJECT_DIR = "/content/drive/MyDrive/XIPL_SDE_Assessment/Q1"

print("Project:", PROJECT_DIR)
print("Persons :", os.listdir(f"{PROJECT_DIR}/person"))
print("Garments:", os.listdir(f"{PROJECT_DIR}/garment"))

os.makedirs(f"{PROJECT_DIR}/output", exist_ok=True)

import sys
import types
import importlib.machinery

fake_flash_attn = types.ModuleType("flash_attn")
fake_flash_attn.__version__ = "2.5.8"
fake_flash_attn.__spec__ = importlib.machinery.ModuleSpec("flash_attn", loader=None)
sys.modules["flash_attn"] = fake_flash_attn

fake_interface = types.ModuleType("flash_attn.flash_attn_interface")
fake_interface.__spec__ = importlib.machinery.ModuleSpec("flash_attn.flash_attn_interface", loader=None)
sys.modules["flash_attn.flash_attn_interface"] = fake_interface

import torch
from PIL import Image
from transformers import AutoModel, AutoTokenizer

MODEL_ID = "openbmb/MiniCPM-V-2_6-int4"

print("Loading model (first run downloads ~7GB, cached to Drive after)...")
vlm_model = AutoModel.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    attn_implementation="sdpa",
)
vlm_model.eval()
vlm_tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
print("Model loaded. Device:", next(vlm_model.parameters()).device)

from pydantic import BaseModel, ValidationError
from typing import Literal, Optional


class GarmentAttributes(BaseModel):
    type: str
    sleeve_length: Literal[
        "sleeveless",
        "short",
        "3/4",
        "long",
        "not_applicable",
        "unknown"
    ]
    neckline: str
    primary_color: str
    pattern: str


class PersonAttributes(BaseModel):
    pose_category: Literal[
        "front-facing",
        "side",
        "seated",
        "unknown"
    ]
    upper_body_visible: bool
    lower_body_visible: bool


class GarmentPersonResult(BaseModel):
    person_image: str
    garment_image: str
    garment_attributes: GarmentAttributes
    person_attributes: PersonAttributes
    model_used: str
    confidence_notes: Optional[str] = ""


print("✅ Q1 output schema ready")

import json
import re

MAX_EDGE = 1024

def load_and_resize(image_path: str) -> Image.Image:
    img = Image.open(image_path).convert("RGB")
    w, h = img.size
    scale = MAX_EDGE / max(w, h)
    if scale < 1.0:
        img = img.resize((int(w * scale), int(h * scale)))
    return img

def _extract_json(text: str) -> dict:
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise ValueError(f"No JSON object found in response: {text[:200]}")
    return json.loads(match.group(0))

# PERSON_PROMPT = """You are a precise image annotator. Look at the photo of a person and output
# ONLY a single JSON object -- no prose, no markdown fences, no explanation.

# Definitions:
# - "front-facing": both shoulders and both sides of the torso are visible in frontward direction;
#    person faces the camera or is close to facing it.
# - "side": person is turned enough that only one shoulder/side of the body is clearly visible.
# - "seated": person is sitting down -- knees are visibly bent and hips are at or below knee height
#   in the frame. This takes priority over facing direction: a seated person facing the camera is
#   still classified as "seated", not "front-facing".
# - "unknown": pose cannot be determined (e.g. person too small/cropped/obscured in frame).

# Ignore direction of face when classifying and focus on the direction of the body.

# upper_body_visible: true if shoulders, chest, or torso area is visible anywhere in the frame, even
# partially. false only if the upper body is entirely cropped out or fully hidden.
# lower_body_visible: true if legs, knees, or anything below the waist is visible anywhere in the
# frame, even partially. false only if the lower body is entirely cropped out or fully hidden.

# Use exactly these keys:
# {
#   "pose_category": "<one of: front-facing, side, seated, unknown>",
#   "upper_body_visible": <true or false>,
#   "lower_body_visible": <true or false>,
#   "confidence_notes": "<short note on anything occluded, cropped, or ambiguous; empty string if none>"
# }

# Example output:
# {
#    "pose_category": "front-facing",
#    "upper_body_visible": true,
#    "lower_body_visible": true,
#    "confidence_notes": "lower legs partially cropped at frame edge"
# }

# Now analyze the given person image and return ONLY the JSON object."""

PERSON_PROMPT = """You are a precise image annotator. Look at the photo of a person and return
ONLY a JSON object -- no prose, no markdown fences.

Work out each field in order, then use your earlier answers to fill in the later ones.

1. description: 1-2 sentences on what the person is doing, their orientation, and any occlusion.

2. torso_direction: which way the torso/chest is turned.
   - facing_camera: both shoulders and both sides of the chest are visible
   - facing_left / facing_right: one shoulder is toward camera, the other turned away or barely
     visible (includes strong three-quarter turns, not just full profile)
   - facing_away: back is to camera
   - unknown: cannot tell

3. head_direction: same options as torso_direction, but for the head/face. It can differ from
   torso_direction (e.g. torso turned sideways, face looking at camera) -- judge independently.

4. posture: standing, seated, or unknown.
   "seated" = sitting on any surface (chair, bench, floor, etc.), or knees visibly bent with
   hips at/below knee height.

5. visible_parts: list every body part visible anywhere in frame, even partially. Choose from:
   head, left_shoulder, right_shoulder, left_arm, right_arm, torso, hips, left_leg, right_leg,
   left_foot, right_foot.

6. pose_category: derive from posture and torso_direction, in this order:
   - posture is seated -> "seated" (overrides torso_direction no matter which way they face)
   - else torso_direction is facing_camera -> "front-facing"
   - else torso_direction is facing_left/right/away -> "side"
   - else -> "unknown"

7. upper_body_visible / lower_body_visible:
   - upper_body_visible = true if any meaningful upper-body region such as shoulders,
     arms, chest, or torso is visible
   - lower_body_visible = true if hips, legs, knees, or feet are visible

IMPORTANT:
- Classify pose primarily from body posture and torso orientation, not only face direction.
- A seated person remains "seated" even if facing directly toward the camera.
- Crossed arms alone do not mean the person is side-facing.
- If no person is visible, use:
  pose_category = "unknown",
  posture = "unknown",
  upper_body_visible = false,
  lower_body_visible = false.

Return exactly these keys, in this order:

{
  "description": "<1-2 sentences>",
  "torso_direction": "<facing_camera, facing_left, facing_right, facing_away, unknown>",
  "head_direction": "<facing_camera, facing_left, facing_right, facing_away, unknown>",
  "posture": "<standing, seated, unknown>",
  "visible_parts": ["<body parts>"],
  "pose_category": "<front-facing, side, seated, unknown>",
  "upper_body_visible": <true/false>,
  "lower_body_visible": <true/false>,
  "confidence_notes": "<short note on occlusion/ambiguity, or empty string>"
}

Example:

{
  "description": "A person stands facing the camera directly, both shoulders square to the camera, arms relaxed at their sides. Cropped just above the knees.",
  "torso_direction": "facing_camera",
  "head_direction": "facing_camera",
  "posture": "standing",
  "visible_parts": ["head", "left_shoulder", "right_shoulder", "left_arm", "right_arm", "torso", "hips", "left_leg", "right_leg"],
  "pose_category": "front-facing",
  "upper_body_visible": true,
  "lower_body_visible": true,
  "confidence_notes": "feet not visible, image cropped above the knees"
}

Now analyze the given person image and return ONLY the JSON object."""

def get_person_attributes(person_image_path: str) -> dict:
    image = load_and_resize(person_image_path)

    # =====================================================
    # PASS 1 — General person analysis
    # =====================================================
    msgs = [
        {
            "role": "user",
            "content": [image, PERSON_PROMPT]
        }
    ]

    response = vlm_model.chat(
        image=None,
        msgs=msgs,
        tokenizer=vlm_tokenizer,
        sampling=False,
        max_new_tokens=500
    )

    print("RAW PERSON RESPONSE:", response)

    try:
        parsed = _extract_json(response)
    except Exception as e:
        return {
            "description": "",
            "torso_direction": "unknown",
            "head_direction": "unknown",
            "posture": "unknown",
            "visible_parts": [],
            "pose_category": "unknown",
            "upper_body_visible": False,
            "lower_body_visible": False,
            "confidence_notes": f"PARSE_FAILED: {e}"
        }
        # =====================================================
    # NO-PERSON GUARD
    # =====================================================

    torso = str(
        parsed.get("torso_direction", "unknown")
    ).strip().lower()

    posture = str(
        parsed.get("posture", "unknown")
    ).strip().lower()

    visible_parts = parsed.get("visible_parts", [])

    upper_visible = parsed.get(
        "upper_body_visible",
        False
    )

    lower_visible = parsed.get(
        "lower_body_visible",
        False
    )

    confidence_notes = str(
        parsed.get("confidence_notes", "")
    ).lower()

    # Strong evidence that no human is present.
    no_person_detected = (
        (
            torso == "unknown"
            and posture == "unknown"
            and upper_visible is False
            and lower_visible is False
        )
        or "no person visible" in confidence_notes
        or "no person" in confidence_notes
    )

    if no_person_detected:
        print("NO PERSON DETECTED: True")

        parsed["pose_category"] = "unknown"
        parsed["upper_body_visible"] = False
        parsed["lower_body_visible"] = False

        return parsed

    print("NO PERSON DETECTED: False")

    # =====================================================
    # PASS 2 — Focused seated detection
    # =====================================================
    posture_prompt = """
Inspect ALL people visible in this image.

Determine whether at least one clearly visible person is SEATED.

A seated person has body weight supported by a chair, sofa,
bench, bed, floor, platform, or another surface.

Look for:
- supported hips
- bent knees
- sitting on a couch/chair/bench
- sitting posture even when torso is upright

Do NOT classify crossed arms alone as seated.

Return ONLY valid JSON:

{"seated_person_present": true}

or

{"seated_person_present": false}
"""

    posture_msgs = [
        {
            "role": "user",
            "content": [image, posture_prompt]
        }
    ]

    try:
        posture_response = vlm_model.chat(
            image=None,
            msgs=posture_msgs,
            tokenizer=vlm_tokenizer,
            sampling=False,
            max_new_tokens=150
        )

        print("RAW POSTURE RESPONSE:", posture_response)

        # First try proper JSON.
        try:
            posture_data = _extract_json(posture_response)

            seated_present = (
                posture_data.get(
                    "seated_person_present",
                    False
                ) is True
            )

        # MiniCPM sometimes answers correctly in prose
        # but produces malformed/truncated JSON.
        except Exception:
            text = posture_response.lower()

            positive_phrases = [
                "there is at least one clearly visible person who is seated",
                "at least one clearly visible person who is seated",
                "person who is seated",
                "person is seated",
                "person on the left side of the image is sitting",
                "person on the right side of the image is sitting",
                "sitting on a couch",
                "sitting on a chair",
                "seated posture"
            ]

            negative_phrases = [
                "not seated",
                "no seated person",
                "no person is seated",
                "there is no",
                "standing and not seated"
            ]

            # Negative evidence gets priority.
            if any(p in text for p in negative_phrases):
                seated_present = False

            elif any(p in text for p in positive_phrases):
                seated_present = True

            else:
                seated_present = False

    except Exception as e:
        print("Posture check failed:", e)
        seated_present = False

    print("SEATED DETECTED:", seated_present)

    # =====================================================
    # SEATED HAS HIGHEST PRIORITY
    # =====================================================
    if seated_present:
        parsed["posture"] = "seated"
        parsed["pose_category"] = "seated"
        return parsed
        # =====================================================
    # PASS 3 — Decide whether orientation needs re-checking
    # =====================================================

    torso = str(
        parsed.get("torso_direction", "unknown")
    ).strip().lower()

    description = str(
        parsed.get("description", "")
    ).strip().lower()

    # If main VLM already detects side orientation,
    # trust the structured result.
    if torso in {
        "facing_left",
        "facing_right",
        "facing_away"
    }:
        parsed["pose_category"] = "side"
        return parsed

    # Only ambiguous/action poses need the extra
    # orientation voting step.
    side_activity_cues = [
        "reaching",
        "reaching out",
        "turned",
        "turning",
        "sideways",
        "towards a",
        "toward a",
        "looking over"
    ]

    needs_orientation_recheck = any(
        cue in description
        for cue in side_activity_cues
    )

    print(
        "ORIENTATION RECHECK NEEDED:",
        needs_orientation_recheck
    )

    # Normal frontal image:
    # trust the original VLM result and DO NOT vote.
    if (
        torso == "facing_camera"
        and not needs_orientation_recheck
    ):
        parsed["pose_category"] = "front-facing"
        return parsed

    # =====================================================
    # PASS 4 — Torso orientation voting
    # =====================================================

    # =====================================================
    # PASS 3 — Torso orientation voting
    # =====================================================
    orientation_prompt = """
Analyze ONLY the MAIN PERSON'S BODY ORIENTATION.

Ignore:
- face direction
- gaze direction
- arms and hands
- activity

Focus ONLY on:
- chest direction
- torso rotation
- shoulder alignment

SIDE means:
- torso is rotated sideways, OR
- body is in a strong three-quarter pose, OR
- one shoulder/side is more prominent than the other.

IMPORTANT:
A person's face may look directly at the camera while their
BODY is still side-facing.

FRONT-FACING means:
- chest is substantially square toward the camera
- torso appears approximately symmetric
- neither shoulder is substantially advanced

Return ONLY:

{"body_orientation": "side"}

or

{"body_orientation": "front-facing"}
"""

    votes = []

    for vote_num in range(3):
        orientation_msgs = [
            {
                "role": "user",
                "content": [image, orientation_prompt]
            }
        ]

        try:
            orientation_response = vlm_model.chat(
                image=None,
                msgs=orientation_msgs,
                tokenizer=vlm_tokenizer,
                sampling=False,
                max_new_tokens=50
            )

            print(
                f"ORIENTATION VOTE {vote_num + 1}:",
                orientation_response
            )

            orientation_data = _extract_json(
                orientation_response
            )

            vote = str(
                orientation_data.get(
                    "body_orientation",
                    "unknown"
                )
            ).strip().lower()

            if vote in {"side", "front-facing"}:
                votes.append(vote)

        except Exception as e:
            print(
                f"Orientation vote {vote_num + 1} failed:",
                e
            )

    print("ORIENTATION VOTES:", votes)

    # =====================================================
    # FINAL DECISION — majority vote
    # =====================================================
    side_votes = votes.count("side")
    front_votes = votes.count("front-facing")

    if side_votes > front_votes:
        parsed["pose_category"] = "side"

    elif front_votes > side_votes:
        parsed["pose_category"] = "front-facing"

    else:
        # Fallback to original torso result
        torso = str(
            parsed.get(
                "torso_direction",
                "unknown"
            )
        ).strip().lower()

        if torso in {
            "facing_left",
            "facing_right",
            "facing_away"
        }:
            parsed["pose_category"] = "side"

        elif torso == "facing_camera":
            parsed["pose_category"] = "front-facing"

        else:
            parsed["pose_category"] = "unknown"

    return parsed

GARMENT_PROMPT = """You are a precise fashion attribute annotator. Look at the garment in the image
and output ONLY a single JSON object -- no prose, no markdown fences, no explanation.

Use exactly these keys:
{
  "type": "<e.g. t-shirt, blouse, jeans, dress, jacket, skirt, sweater, hoodie, shorts>",
  "sleeve_length": "<one of: sleeveless, short, 3/4, long, not_applicable, unknown>",
  "neckline": "<e.g. crew, v-neck, collared, scoop, turtleneck, halter, off-shoulder, not_applicable, unknown>",
  "primary_color": "<single dominant color, lowercase, 1-2 words max>",
  "pattern": "<e.g. solid, striped, graphic print, floral, plaid, polka dot, animal print, unknown>",
  "confidence_notes": "<short note on anything occluded, ambiguous, or uncertain; empty string if none>"
}

Notes:
- sleeve_length "not_applicable" is for garments with no sleeves by design (e.g. pants, skirts).
- sleeve_length "unknown" is for garments that do have sleeves but length can't be determined (e.g. cropped out of frame).

Example output:
{
    "type": "t-shirt",
    "sleeve_length": "short",
    "neckline": "crew",
    "primary_color": "white",
    "pattern": "graphic print",
    "confidence_notes": "Pattern detected via close-up region"
  }

Now analyze the given garment image and return ONLY the JSON object."""

def get_garment_attributes(garment_image_path: str, max_retries: int = 1) -> dict:
    image = load_and_resize(garment_image_path)
    msgs = [{"role": "user", "content": [image, GARMENT_PROMPT]}]

    last_error = None
    for attempt in range(max_retries + 1):
        prompt = GARMENT_PROMPT
        if attempt > 0:
            prompt = GARMENT_PROMPT + f"\n\nYour previous response was invalid JSON or missing required keys ({last_error}). Fix it and return ONLY the corrected JSON object."
            msgs = [{"role": "user", "content": [image, prompt]}]

        response = vlm_model.chat(
            image=None, msgs=msgs, tokenizer=vlm_tokenizer,
            sampling=False, max_new_tokens=600
        )
        try:
            parsed = _extract_json(response)
            required = {"type", "sleeve_length", "neckline", "primary_color", "pattern"}
            if not required.issubset(parsed.keys()):
                raise ValueError(f"missing keys: {required - parsed.keys()}")
            return parsed
        except (ValueError, json.JSONDecodeError) as e:
            last_error = str(e)
            continue

    return {
        "type": "unknown", "sleeve_length": "unknown", "neckline": "unknown",
        "primary_color": "unknown", "pattern": "unknown",
        "confidence_notes": f"PARSE_FAILED after {max_retries + 1} attempts: {last_error}"
    }

def process_pair(person_image_path: str, garment_image_path: str) -> dict:

    # Run VLM inference
    person_result = get_person_attributes(person_image_path)
    garment_result = get_garment_attributes(garment_image_path)

    # Extract confidence notes
    person_notes = person_result.get("confidence_notes", "") or ""
    garment_notes = garment_result.get("confidence_notes", "") or ""

    combined_notes = " ; ".join(
        note for note in [garment_notes, person_notes] if note
    )

    # Build ONLY the final fields required by Q1
    record = {
        "person_image": os.path.basename(person_image_path),

        "garment_image": os.path.basename(garment_image_path),

        "garment_attributes": {
            "type": garment_result.get("type", "unknown"),
            "sleeve_length": garment_result.get(
                "sleeve_length", "unknown"
            ),
            "neckline": garment_result.get(
                "neckline", "unknown"
            ),
            "primary_color": garment_result.get(
                "primary_color", "unknown"
            ),
            "pattern": garment_result.get(
                "pattern", "unknown"
            ),
        },

        "person_attributes": {
            "pose_category": person_result.get(
                "pose_category", "unknown"
            ),
            "upper_body_visible": bool(
                person_result.get("upper_body_visible", False)
            ),
            "lower_body_visible": bool(
                person_result.get("lower_body_visible", False)
            ),
        },

        "model_used": "MiniCPM-V-2_6-int4",

        "confidence_notes": combined_notes,
    }

    # Validate FINAL output
    try:
        validated = GarmentPersonResult(**record)
        print("✅ Schema validation passed")

    except ValidationError as e:
        print("❌ Schema validation failed")
        print(e)
        raise

    return record

person_path = f"{PROJECT_DIR}/person/person_01.png"
garment_path = f"{PROJECT_DIR}/garment/garment_01.jpg"

result = process_pair(
    person_path,
    garment_path
)

print(json.dumps(result, indent=2))

import os

print("PERSON FILES:")
for f in sorted(os.listdir(PERSON_DIR)):
    print(f)

print("\nGARMENT FILES:")
for f in sorted(os.listdir(GARMENT_DIR)):
    print(f)

import os
import json
import re

person_files = sorted([
    f for f in os.listdir(PERSON_DIR)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
])

garment_files = sorted([
    f for f in os.listdir(GARMENT_DIR)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
])

print("Persons :", len(person_files))
print("Garments:", len(garment_files))

results = []

pair_count = min(
    len(person_files),
    len(garment_files)
)

print("Processing", pair_count, "pairs")

for i in range(pair_count):

    person_path = os.path.join(
        PERSON_DIR,
        person_files[i]
    )

    garment_path = os.path.join(
        GARMENT_DIR,
        garment_files[i]
    )

    print(
        f"\nProcessing pair {i+1}/{pair_count}"
    )

    result = process_pair(
        person_path,
        garment_path
    )

    results.append(result)

print("\n✅ Normal pairs completed:", len(results))

EDGE_DIR = f"{PROJECT_DIR}/edge_cases"

print(os.listdir(EDGE_DIR))

def process_person_only(person_image_path: str) -> dict:

    person_result = get_person_attributes(
        person_image_path
    )

    result = {
        "person_image": os.path.basename(
            person_image_path
        ),

        "person_attributes": {
            "pose_category": person_result.get(
                "pose_category", "unknown"
            ),

            "upper_body_visible": bool(
                person_result.get(
                    "upper_body_visible", False
                )
            ),

            "lower_body_visible": bool(
                person_result.get(
                    "lower_body_visible", False
                )
            ),
        },

        "model_used": "MiniCPM-V-2_6-int4",

        "confidence_notes": person_result.get(
            "confidence_notes", ""
        )
    }

    return result

EDGE_DIR = f"{PROJECT_DIR}/edge_cases"

edge_case_files = [
    f for f in sorted(os.listdir(EDGE_DIR))
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
]

print("Edge-case images found:", len(edge_case_files))

for f in edge_case_files:
    print(" -", f)

import pandas as pd
import os

manifest_path = os.path.join(
    PROJECT_DIR,
    "edge_cases",
    "edge_cases_manifest.csv"
)

manifest = pd.read_csv(manifest_path)

display(manifest)

PERSON_DIR = os.path.join(PROJECT_DIR, "person")
GARMENT_DIR = os.path.join(PROJECT_DIR, "garment")

print("PERSON_DIR:", PERSON_DIR)
print("Exists:", os.path.exists(PERSON_DIR))

print("\nGARMENT_DIR:", GARMENT_DIR)
print("Exists:", os.path.exists(GARMENT_DIR))


person_files = sorted([
    f for f in os.listdir(PERSON_DIR)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
])

garment_files = sorted([
    f for f in os.listdir(GARMENT_DIR)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
])


print("\n===== PERSON IMAGES =====")
print("Count:", len(person_files))

for f in person_files:
    print(" -", f)


print("\n===== GARMENT IMAGES =====")
print("Count:", len(garment_files))

for f in garment_files:
    print(" -", f)

test_pairs = []

for i in range(1, 6):
    person_name = f"person_{i:02d}.png"
    garment_name = f"garment_{i:02d}.jpg"

    person_path = os.path.join(PERSON_DIR, person_name)
    garment_path = os.path.join(GARMENT_DIR, garment_name)

    test_pairs.append({
        "pair_id": f"pair_{i:02d}",
        "person_image": person_name,
        "garment_image": garment_name,
        "person_path": person_path,
        "garment_path": garment_path
    })

print("===== Q1 TEST PAIRS =====")

for pair in test_pairs:
    print(
        f"{pair['pair_id']}: "
        f"{pair['person_image']} + {pair['garment_image']}"
    )

print("\nTotal pairs:", len(test_pairs))

test_garment = os.path.join(
    GARMENT_DIR,
    "garment_01.jpg"
)

garment_result = get_garment_attributes(test_garment)

print("\n===== GARMENT TEST =====")
print(json.dumps(garment_result, indent=2))

pair = test_pairs[0]

print("Processing:", pair["pair_id"])
print("Person:", pair["person_image"])
print("Garment:", pair["garment_image"])

person_attrs = get_person_attributes(pair["person_path"])
garment_attrs = get_garment_attributes(pair["garment_path"])

pair_result = {
    "pair_id": pair["pair_id"],
    "person_image": pair["person_image"],
    "garment_image": pair["garment_image"],
    "garment_attributes": {
        "type": garment_attrs.get("type", "unknown"),
        "sleeve_length": garment_attrs.get("sleeve_length", "unknown"),
        "neckline": garment_attrs.get("neckline", "unknown"),
        "primary_color": garment_attrs.get("primary_color", "unknown"),
        "pattern": garment_attrs.get("pattern", "unknown")
    },
    "person_attributes": {
        "pose_category": person_attrs.get("pose_category", "unknown"),
        "upper_body_visible": person_attrs.get("upper_body_visible", False),
        "lower_body_visible": person_attrs.get("lower_body_visible", False)
    }
}

print("\n===== COMPLETE PAIR 01 RESULT =====")
print(json.dumps(pair_result, indent=2))

q1_edge_files = [
    "person_side_pose.jpg",
    "person_seated.jpg"
]

q1_edge_results = []

for filename in q1_edge_files:

    print("\n" + "=" * 60)
    print("TESTING:", filename)
    print("=" * 60)

    path = os.path.join(EDGE_DIR, filename)

    result = process_person_only(path)
    q1_edge_results.append(result)


print("\n===== Q1 REQUIRED EDGE CASE CHECK =====")

expected = {
    "person_side_pose.jpg": "side",
    "person_seated.jpg": "seated"
}

all_passed = True

for result in q1_edge_results:

    filename = result["person_image"]
    predicted = result["person_attributes"]["pose_category"]
    target = expected[filename]

    passed = predicted == target
    all_passed = all_passed and passed

    print(
        f"{'✅' if passed else '❌'} "
        f"{filename}: predicted={predicted}, expected={target}"
    )

if all_passed:
    print("\n🎉 Q1 EDGE-CASE REQUIREMENT PASSED")
else:
    print("\n❌ One or more required cases failed")

all_pair_results = []

print("===== PROCESSING ALL Q1 TEST PAIRS =====")

for pair in test_pairs:

    print("\n" + "=" * 70)
    print("Processing:", pair["pair_id"])
    print("Person:", pair["person_image"])
    print("Garment:", pair["garment_image"])
    print("=" * 70)

    # Person analysis
    person_attrs = get_person_attributes(
        pair["person_path"]
    )

    # Garment analysis
    garment_attrs = get_garment_attributes(
        pair["garment_path"]
    )

    # Final structured result
    result = {
        "pair_id": pair["pair_id"],
        "person_image": pair["person_image"],
        "garment_image": pair["garment_image"],

        "garment_attributes": {
            "type": garment_attrs.get("type", "unknown"),
            "sleeve_length": garment_attrs.get(
                "sleeve_length", "unknown"
            ),
            "neckline": garment_attrs.get(
                "neckline", "unknown"
            ),
            "primary_color": garment_attrs.get(
                "primary_color", "unknown"
            ),
            "pattern": garment_attrs.get(
                "pattern", "unknown"
            )
        },

        "person_attributes": {
            "pose_category": person_attrs.get(
                "pose_category", "unknown"
            ),
            "upper_body_visible": person_attrs.get(
                "upper_body_visible", False
            ),
            "lower_body_visible": person_attrs.get(
                "lower_body_visible", False
            )
        },

        "model_used": "MiniCPM-V-2_6-int4"
    }

    all_pair_results.append(result)

    print("\nFINAL RESULT:")
    print(json.dumps(result, indent=2))


print("\n" + "=" * 70)
print("✅ ALL 5 Q1 PAIRS PROCESSED")
print("Total:", len(all_pair_results))
print("=" * 70)

OUTPUT_DIR = os.path.join(PROJECT_DIR, "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("OUTPUT DIRECTORY:", OUTPUT_DIR)

# Save each pair separately
for result in all_pair_results:
    pair_id = result["pair_id"]

    output_file = os.path.join(
        OUTPUT_DIR,
        f"{pair_id}.json"
    )

    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

    print(f"✅ Saved {pair_id}.json")


# Save all 5 pairs together as well
combined_file = os.path.join(
    OUTPUT_DIR,
    "all_test_pairs_q1.json"
)

with open(combined_file, "w", encoding="utf-8") as f:
    json.dump(all_pair_results, f, indent=2, ensure_ascii=False)

print("✅ Saved all_test_pairs_q1.json")

q1_person_edge_files = [
    "person_crossed_arms.jpg",
    "person_side_pose.jpg",
    "person_seated.jpg"
]

edge_results = []

print("===== PROCESSING Q1 PERSON EDGE CASES =====")

for filename in q1_person_edge_files:

    print("\n" + "=" * 65)
    print("Processing:", filename)
    print("=" * 65)

    path = os.path.join(EDGE_DIR, filename)

    result = process_person_only(path)

    edge_results.append(result)

    # Save individual JSON
    output_name = (
        os.path.splitext(filename)[0] + "_q1.json"
    )

    output_path = os.path.join(
        OUTPUT_DIR,
        output_name
    )

    with open(
        output_path,
        "w",
        encoding="utf-8"
    ) as f:
        json.dump(
            result,
            f,
            indent=2,
            ensure_ascii=False
        )

    print("\nFINAL:")
    print(json.dumps(result, indent=2))
    print("✅ Saved:", output_name)


# Save combined edge-case results
edge_combined_path = os.path.join(
    OUTPUT_DIR,
    "edge_cases_q1.json"
)

with open(
    edge_combined_path,
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        edge_results,
        f,
        indent=2,
        ensure_ascii=False
    )

print("\n✅ Saved edge_cases_q1.json")

print("\n===== EDGE CASE SUMMARY =====")

for result in edge_results:

    print(
        result["person_image"],
        "→",
        result["person_attributes"]["pose_category"]
    )

no_person_path = os.path.join(
    EDGE_DIR,
    "no_person.jpg"
)

print("=" * 60)
print("TESTING: no_person.jpg")
print("=" * 60)

no_person_result = process_person_only(
    no_person_path
)

print("\n===== NO PERSON RESULT =====")
print(
    json.dumps(
        no_person_result,
        indent=2
    )
)

# Save no-person result
no_person_output = os.path.join(
    OUTPUT_DIR,
    "no_person_q1.json"
)

with open(no_person_output, "w", encoding="utf-8") as f:
    json.dump(
        no_person_result,
        f,
        indent=2,
        ensure_ascii=False
    )

print("✅ Saved:", no_person_output)


# Show everything currently in Q1/output
print("\n===== FINAL Q1 OUTPUT FILES =====")

for filename in sorted(os.listdir(OUTPUT_DIR)):
    print(" -", filename)

print("===== SEARCHING FOR sample_output_q1.json =====")

sample_files = []

for root, dirs, files in os.walk("/content/drive/MyDrive/XIPL_SDE_Assessment"):
    for file in files:
        if file == "sample_output_q1.json":
            path = os.path.join(root, file)
            sample_files.append(path)
            print("✅ Found:", path)

if not sample_files:
    print("❌ sample_output_q1.json not found")

SAMPLE_PATH = sample_files[0]

with open(SAMPLE_PATH, "r", encoding="utf-8") as f:
    sample_q1 = json.load(f)

print("\n===== OFFICIAL SAMPLE Q1 OUTPUT =====")
print(json.dumps(sample_q1, indent=2))

# Update already-generated results — NO model rerun needed

for result in all_pair_results:

    # Match official model naming
    result["model_used"] = "MiniCPM-V-2.6"

    # Add required top-level confidence_notes
    if "confidence_notes" not in result:
        result["confidence_notes"] = ""


# Resave individual pair JSON files
for result in all_pair_results:

    pair_id = result["pair_id"]

    output_path = os.path.join(
        OUTPUT_DIR,
        f"{pair_id}.json"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(
            result,
            f,
            indent=2,
            ensure_ascii=False
        )

    print("✅ Updated:", f"{pair_id}.json")


# Resave combined JSON
combined_path = os.path.join(
    OUTPUT_DIR,
    "all_test_pairs_q1.json"
)

with open(combined_path, "w", encoding="utf-8") as f:
    json.dump(
        all_pair_results,
        f,
        indent=2,
        ensure_ascii=False
    )

print("\n✅ All Q1 pair JSON files updated")

# Remove pair_id so individual outputs match sample_output_q1.json

for result in all_pair_results:
    result.pop("pair_id", None)

# Resave pair files
for i, result in enumerate(all_pair_results, start=1):

    output_path = os.path.join(
        OUTPUT_DIR,
        f"pair_{i:02d}.json"
    )

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2, ensure_ascii=False)

# Resave combined output
combined_path = os.path.join(
    OUTPUT_DIR,
    "all_test_pairs_q1.json"
)

with open(combined_path, "w", encoding="utf-8") as f:
    json.dump(all_pair_results, f, indent=2, ensure_ascii=False)

print("✅ Removed pair_id and resaved outputs")

sample_keys = set(sample_q1.keys())
sample_garment_keys = set(
    sample_q1["garment_attributes"].keys()
)
sample_person_keys = set(
    sample_q1["person_attributes"].keys()
)

print("===== Q1 SCHEMA VALIDATION =====")

all_valid = True

for i, result in enumerate(all_pair_results, start=1):

    top_ok = set(result.keys()) == sample_keys

    garment_ok = (
        set(result["garment_attributes"].keys())
        == sample_garment_keys
    )

    person_ok = (
        set(result["person_attributes"].keys())
        == sample_person_keys
    )

    valid = top_ok and garment_ok and person_ok
    all_valid = all_valid and valid

    print(
        f"{'✅' if valid else '❌'} pair_{i:02d}: "
        f"top={top_ok}, "
        f"garment={garment_ok}, "
        f"person={person_ok}"
    )

if all_valid:
    print("\n🎉 ALL 5 OUTPUTS MATCH THE OFFICIAL Q1 SCHEMA")
else:
    print("\n❌ Schema mismatch found")

print("===== COMPLETE EDGE-CASE VALIDATION =====")

edge_files = [
    "person_crossed_arms_q1.json",
    "person_side_pose_q1.json",
    "person_seated_q1.json",
    "no_person_q1.json"
]

for filename in edge_files:

    path = os.path.join(OUTPUT_DIR, filename)

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    attrs = data["person_attributes"]

    print(
        f"{filename}: "
        f"pose={attrs['pose_category']}, "
        f"upper={attrs['upper_body_visible']}, "
        f"lower={attrs['lower_body_visible']}"
    )

readme = """# Q1 - Garment & Body Understanding with a Vision-Language Model

## Objective

This task uses an open Vision-Language Model (VLM) to analyze a person image and a garment image and produce structured JSON attributes.

For each person-garment pair, the system extracts:

### Garment Attributes
- Type
- Sleeve length
- Neckline
- Primary color
- Pattern

### Person Attributes
- Pose category: `front-facing`, `side`, `seated`, or `unknown`
- Upper-body visibility
- Lower-body visibility

The final outputs follow the structure provided in `sample_output_q1.json`.

---

## Model Used

**MiniCPM-V 2.6 (INT4)**

- Framework: Hugging Face Transformers
- Inference: PyTorch
- Quantization: INT4
- Runtime: Google Colab
- Hardware: NVIDIA Tesla T4 GPU

### Why MiniCPM-V 2.6?

MiniCPM-V 2.6 was selected because it provides strong image understanding and instruction-following capabilities while remaining practical for Google Colab GPU environments.

The INT4 quantized version reduces GPU memory requirements, making inference feasible on a Tesla T4 while retaining the multimodal capabilities required for garment attribute extraction and human pose understanding.

It was suitable for this task because the same model can analyze both garment appearance and person/body information and return structured responses through carefully designed prompts.

---

## Pipeline

The Q1 pipeline follows these stages:

1. Load the person and garment images.
2. Resize large images while preserving aspect ratio.
3. Analyze the garment image using MiniCPM-V.
4. Extract:
   - garment type
   - sleeve length
   - neckline
   - primary color
   - pattern
5. Analyze the person image using MiniCPM-V.
6. Extract body orientation, posture, visible body parts, and visibility information.
7. Apply pose decision logic to obtain:
   - front-facing
   - side
   - seated
   - unknown
8. Apply additional checks for difficult pose cases.
9. Convert the model response into structured JSON.
10. Save the results in the `output/` directory.

---

## Pose Classification and Edge-Case Handling

The person-analysis pipeline uses structured VLM reasoning together with lightweight post-processing rules.

### Seated Detection

Seated posture has the highest priority. A focused second-pass check is used for difficult seated images.

If a seated person is detected:

`pose_category = "seated"`

This takes priority over body orientation.

### Side-Pose Detection

For potentially ambiguous body orientations, a focused torso-orientation check is performed.

The system focuses on torso and shoulder orientation rather than only face direction. Multiple orientation predictions are used for difficult cases to improve robustness.

### No-Person Detection

If the VLM reports no visible person and both upper- and lower-body visibility are false, the result is:

- `pose_category = "unknown"`
- `upper_body_visible = false`
- `lower_body_visible = false`

This output is also useful for the no-person guardrail used later in Q5.

---

## Edge Cases

The supplied edge-case images were tested separately.

Important required cases include:

- `person_side_pose.jpg` -> `side`
- `person_seated.jpg` -> `seated`
- `no_person.jpg` -> `unknown` with no upper/lower body detected

`person_crossed_arms.jpg` was also processed as part of the supplied edge-case set.

---

## Output Format

Example:

{
  "person_image": "person_01.png",
  "garment_image": "garment_01.jpg",
  "garment_attributes": {
    "type": "t-shirt",
    "sleeve_length": "short",
    "neckline": "crew",
    "primary_color": "purple",
    "pattern": "solid"
  },
  "person_attributes": {
    "pose_category": "front-facing",
    "upper_body_visible": true,
    "lower_body_visible": true
  },
  "model_used": "MiniCPM-V-2.6",
  "confidence_notes": ""
}

---

## Folder Structure

Q1/
├── person/
│   ├── person_01.png
│   ├── ...
│   └── person_05.png
├── garment/
│   ├── garment_01.jpg
│   ├── ...
│   └── garment_05.jpg
├── edge_cases/
├── output/
│   ├── pair_01.json
│   ├── pair_02.json
│   ├── pair_03.json
│   ├── pair_04.json
│   ├── pair_05.json
│   ├── all_test_pairs_q1.json
│   └── edge-case JSON outputs
├── Q1.ipynb
└── README.md

---

## Libraries Used

- PyTorch
- Transformers
- Pillow
- Pydantic
- SentencePiece
- Accelerate
- BitsAndBytes

---

## Implementation Notes

- Images are resized while preserving their aspect ratio.
- Model responses are parsed into structured JSON.
- JSON extraction includes fallback handling for malformed VLM responses.
- Deterministic inference is used where possible.
- INT4 quantization reduces GPU memory usage.
- Additional pose checks improve robustness on the supplied seated and side-pose edge cases.
- Final pair outputs were validated against the structure of `sample_output_q1.json`.

---

## Author

Nandana R
B.Tech Computer Science (Artificial Intelligence)
"""

with open(f"{PROJECT_DIR}/README.md", "w", encoding="utf-8") as f:
    f.write(readme)

print("✅ Final Q1 README updated successfully!")
print(f"{PROJECT_DIR}/README.md")

