# -*- coding: utf-8 -*-
"""Q5_(2) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Co3OiXZZW8PomKzuL3vPdgGfSSmFf1RU

Q5 Mini Try on Demo
"""

# !pip install -q \
#   numpy \
#   scipy \
#   transformers==4.44.2 \
#   diffusers==0.30.3 \
#   accelerate==0.30.1 \
#   peft==0.11.1 \
#   gradio==4.44.1 \
#   gradio_client==1.3.0 \
#   open_clip_torch \
#   fvcore \
#   iopath \
#   omegaconf \
#   opencv-python \
#   scikit-image \
#   pillow \
#   av \
#   huggingface_hub

!pip install -q \
  numpy \
  scipy \
  transformers==4.44.2 \
  diffusers==0.30.3 \
  accelerate==0.30.1 \
  peft==0.11.1 \
  "gradio>=5.0,<6.0" \
  open_clip_torch \
  fvcore \
  iopath \
  omegaconf \
  opencv-python \
  scikit-image \
  pillow \
  av \
  ultralytics \
  "huggingface_hub<1.0,>=0.23.2"

print("✅ Packages installed.")
print("⚠️ Click Runtime → Restart session, then re-run your notebook from the top.")

# Commented out IPython magic to ensure Python compatibility.
# ==========================
# Q5 CELL 2
# ==========================

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil

if os.path.exists("/content/CatVTON"):
    shutil.rmtree("/content/CatVTON")

# %cd /content

!git clone https://github.com/Zheng-Chong/CatVTON.git

# %cd /content/CatVTON

print("✅ CatVTON cloned successfully")

!ls /content/CatVTON/model

# ==========================
# Q5 CELL 3
# Download CatVTON Checkpoints
# ==========================

from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="zhengchong/CatVTON",
    local_dir="/content/CatVTON/checkpoints/CatVTON",
    local_dir_use_symlinks=False
)

print("✅ CatVTON checkpoints downloaded")

import os

print(os.path.exists("/content/CatVTON/checkpoints/CatVTON"))

!find /content/CatVTON/checkpoints/CatVTON -maxdepth 2 -type f | head -20

# ==========================
# Q5 CELL 4
# Import CatVTON
# ==========================

import os
import sys

os.chdir("/content/CatVTON")

if "/content/CatVTON" not in sys.path:
    sys.path.insert(0, "/content/CatVTON")

# Create __init__.py if missing
init_file="/content/CatVTON/model/__init__.py"

if not os.path.exists(init_file):
    open(init_file,"w").close()

from model.pipeline import CatVTONPipeline
from model.cloth_masker import AutoMasker
from utils import init_weight_dtype

print("✅ Imports Successful")

# ==========================
# Q5 CELL 5
# Load CatVTON
# ==========================

import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

weight_dtype = init_weight_dtype("fp16")

pipeline = CatVTONPipeline(
    base_ckpt="booksforcharlie/stable-diffusion-inpainting",
    attn_ckpt="/content/CatVTON/checkpoints/CatVTON",
    attn_ckpt_version="mix",
    weight_dtype=weight_dtype,
    device=device,
)

auto_masker = AutoMasker(
    densepose_ckpt="/content/CatVTON/checkpoints/CatVTON/DensePose",
    schp_ckpt="/content/CatVTON/checkpoints/CatVTON/SCHP",
    device=device,
)

print("✅ Pipeline Loaded")

print(type(pipeline))
print(type(auto_masker))

# ==========================
# Q5 CELL 6
# OpenCLIP Model
# ==========================

import open_clip
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

model, _, preprocess = open_clip.create_model_and_transforms(
    "ViT-B-32",
    pretrained="laion2b_s34b_b79k"
)

model = model.to(device)
model.eval()

print("✅ OpenCLIP Loaded")

from PIL import Image
import numpy as np
from skimage.metrics import structural_similarity

def clip_similarity(img1_path, img2_path):

    img1 = preprocess(Image.open(img1_path)).unsqueeze(0).to(device)
    img2 = preprocess(Image.open(img2_path)).unsqueeze(0).to(device)

    with torch.no_grad():

        feat1 = model.encode_image(img1)
        feat2 = model.encode_image(img2)

        feat1 /= feat1.norm(dim=-1, keepdim=True)
        feat2 /= feat2.norm(dim=-1, keepdim=True)

    return (feat1 @ feat2.T).item()


def identity_score(person_path, output_path):

    person = Image.open(person_path).convert("L").resize((256,256))
    output = Image.open(output_path).convert("L").resize((256,256))

    return structural_similarity(
        np.array(person),
        np.array(output),
        data_range=255
    )


def judge_score(garment,idt):

    overall=(garment+idt)/2

    if overall>0.80:
        score=9
        reason="Excellent try-on quality"

    elif overall>0.70:
        score=8
        reason="Good try-on quality"

    elif overall>0.60:
        score=7
        reason="Acceptable quality"

    else:
        score=6
        reason="Visible artifacts"

    return score,reason

print("✅ Evaluation Loaded")

!pip -q install ultralytics

from ultralytics import YOLO

yolo = YOLO("yolov8n.pt")

print("✅ YOLO Loaded")

import numpy as np

def check_guardrails(person_img):

    # Detect people
    results = yolo.predict(person_img, verbose=False)

    person_found = False

    for box in results[0].boxes:
        cls = int(box.cls[0])

        # COCO class 0 = person
        if cls == 0:
            person_found = True

            x1, y1, x2, y2 = box.xyxy[0].tolist()

            w = x2 - x1
            h = y2 - y1

            # Very simple pose heuristic
            if w > h:
                return True, "⚠️ Warning: Side pose detected."

            if h / w < 1.4:
                return True, "⚠️ Warning: Person may be seated."

            return True, "✅ Suitable pose."

    return False, "❌ No person detected."

import inspect
print(inspect.signature(pipeline.__call__))

import tempfile
import time
from PIL import Image

def run_virtual_tryon(person_img, garment_img):

    start = time.time()

    # Save temporary images
    person_path = tempfile.mktemp(suffix=".png")
    garment_path = tempfile.mktemp(suffix=".png")

    person_img.save(person_path)
    garment_img.save(garment_path)

    # -----------------------------
    # Guardrails
    # -----------------------------
    ok, message = check_guardrails(person_img)

    if not ok:
        return None, message, "", "", ""

    # -----------------------------
    # Generate Mask
    # -----------------------------
    mask_dict = auto_masker(person_img, "upper")

    mask = mask_dict["mask"]

    # -----------------------------
    # Run CatVTON
    # -----------------------------
    result = pipeline(
        image=person_img,
        condition_image=garment_img,
        mask=mask,
        num_inference_steps=30,
        guidance_scale=2.5,
        height=1024,
        width=768,
    )

    # Some versions return a list, others return a PIL image
    if isinstance(result, list):
        result = result[0]

    output_path = tempfile.mktemp(suffix=".png")
    result.save(output_path)

    # -----------------------------
    # Evaluation
    # -----------------------------
    garment = clip_similarity(
        garment_path,
        output_path
    )

    identity = identity_score(
        person_path,
        output_path
    )

    score, reason = judge_score(
        garment,
        identity
    )

    scores = f"""
Garment Fidelity : {garment:.4f}

Identity Preservation : {identity:.4f}

Judge Score : {score}/10

Reason:
{reason}
"""

    processing = f"{time.time()-start:.2f} sec"

    garment_attributes = """
Garment Attributes (Q1)

• Category : Upper Wear
• Color : Auto
• Pattern : Auto
• Sleeve : Auto

(Placeholder for Q1 output)
"""

    return (
        result,
        message,
        garment_attributes,
        scores,
        processing,
    )

print("✅ Main function loaded")

readme = """
# Q5 - Mini Virtual Try-On Web Demo

## How to Run in Google Colab

1. Enable GPU
   Runtime → Change runtime type → GPU

2. Run all notebook cells from top to bottom.

3. Upload:
   - Person Image
   - Garment Image

4. Click **Generate Try-On**.

## Features

- Virtual Try-On using CatVTON
- Q1 Garment Attributes
- Q4 Quality Scores
- Person Detection
- Side Pose Warning
- Seated Pose Warning
- Processing Time

## Test Images

- edge_cases/no_person.jpg
- edge_cases/person_seated.jpg
- edge_cases/person_side_pose.jpg

"""

with open("README.md", "w") as f:
    f.write(readme)

print("README created successfully!")

import gradio as gr

demo = gr.Interface(
    fn=run_virtual_tryon,

    inputs=[
        gr.Image(type="pil", label="Person"),
        gr.Image(type="pil", label="Garment"),
    ],

    outputs=[
        gr.Image(label="Try-On Result"),
        gr.Textbox(label="Guardrails"),
        gr.Textbox(label="Garment Attributes"),
        gr.Textbox(label="Quality Scores"),
        gr.Textbox(label="Processing Time"),
    ],

    title="Mini Virtual Try-On Demo",

    description="""
Upload a person image and a garment image.

The application performs:

• Virtual Try-On (CatVTON)

• Quality Evaluation

• Guardrails

• Estimated Processing Time
"""
)

demo.launch(
    share=True,
    debug=True,
    show_api=False
)