# -*- coding: utf-8 -*-
"""Q3 (3).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17vxtZtOtJ3wgzNt7MoVmLTSx-dMtyH77

# Q3 – End-to-End Try-On Inference

Model: CatVTON

GPU: Tesla T4

Preprocessing:
- CatVTON AutoMasker
- Q2 pipeline integration

Outputs:
- output_01.png
- output_02.png
- output_03.png
- output_04.png
- output_05.png
"""

from google.colab import drive
drive.mount('/content/drive')

PROJECT_DIR = "/content/drive/MyDrive/XIPL_SDE_Assessment"

Q2_DIR = f"{PROJECT_DIR}/Q2"
Q3_DIR = f"{PROJECT_DIR}/Q3"

import os

os.makedirs(Q3_DIR, exist_ok=True)
os.makedirs(f"{Q3_DIR}/outputs", exist_ok=True)

print(Q2_DIR)
print(Q3_DIR)

import torch

print(torch.__version__)
print(torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

!rm -rf CatVTON

!git clone https://github.com/Zheng-Chong/CatVTON.git

# %cd CatVTON

!pip install -q \
    diffusers==0.30.3 \
    transformers==4.44.2 \
    accelerate==0.30.1 \
    safetensors \
    sentencepiece \
    opencv-python \
    pillow \
    einops \
    huggingface_hub \
    peft==0.11.1 \
    xformers

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content

import os

if not os.path.exists("CatVTON"):
    !git clone https://github.com/Zheng-Chong/CatVTON.git

# %cd CatVTON

import torch
import diffusers
import transformers
import peft
import accelerate

print("Torch:", torch.__version__)
print("Diffusers:", diffusers.__version__)
print("Transformers:", transformers.__version__)
print("PEFT:", peft.__version__)
print("Accelerate:", accelerate.__version__)
print("GPU:", torch.cuda.get_device_name(0))

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CatVTON

from huggingface_hub import snapshot_download

snapshot_download(
    repo_id="zhengchong/CatVTON",
    local_dir="checkpoints/CatVTON",
    local_dir_use_symlinks=False
)

import os

print(os.path.exists("checkpoints/CatVTON"))

!find checkpoints/CatVTON -maxdepth 2 -type f | head -20

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/CatVTON

import os
import sys

sys.path.append("/content/CatVTON")

print("Current directory:", os.getcwd())

!pip install -q \
fvcore \
iopath \
pyyaml \
omegaconf \
pycocotools

import torch
import fvcore
import iopath

print("Torch :", torch.__version__)
print("fvcore OK")
print("iopath OK")

!pip install -q av

import av
print("PyAV:", av.__version__)

from model.pipeline import CatVTONPipeline
from model.cloth_masker import AutoMasker
from utils import init_weight_dtype

print("✅ Imports Successful")

import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

weight_dtype = init_weight_dtype("fp16")

pipeline = CatVTONPipeline(
    base_ckpt="booksforcharlie/stable-diffusion-inpainting",
    attn_ckpt="./checkpoints/CatVTON",
    attn_ckpt_version="mix",
    weight_dtype=weight_dtype,
    device=device,
)

print("✅ CatVTON Pipeline Loaded")



from PIL import Image
import os

PROJECT_DIR = "/content/drive/MyDrive/XIPL_SDE_Assessment"

PERSON_DIR = f"{PROJECT_DIR}/Q2/dataset/sample_files/test_pairs/person"
GARMENT_DIR = f"{PROJECT_DIR}/Q2/dataset/sample_files/test_pairs/garment"
MASK_DIR = f"{PROJECT_DIR}/Q2/clothing_masks"
OUTPUT_DIR = f"{PROJECT_DIR}/Q3/outputs"

os.makedirs(OUTPUT_DIR, exist_ok=True)

print("Person images:", len(os.listdir(PERSON_DIR)))
print("Garment images:", len(os.listdir(GARMENT_DIR)))
print("Masks:", len(os.listdir(MASK_DIR)))

person_files = sorted(os.listdir(PERSON_DIR))
garment_files = sorted(os.listdir(GARMENT_DIR))
mask_files = sorted(os.listdir(MASK_DIR))

print(person_files)
print(garment_files)
print(mask_files)

person = Image.open(os.path.join(PERSON_DIR, person_files[0])).convert("RGB")
cloth = Image.open(os.path.join(GARMENT_DIR, garment_files[0])).convert("RGB")
mask = Image.open(os.path.join(MASK_DIR, mask_files[0])).convert("L")

print(person.size)
print(cloth.size)
print(mask.size)

from PIL import Image

mask = mask.resize(person.size, Image.NEAREST)

print(person.size)
print(cloth.size)
print(mask.size)

import inspect

print(inspect.signature(pipeline.__call__))

print(type(result))
print(len(result))

print(type(result[0]))

result[0].save(
    os.path.join(
        OUTPUT_DIR,
        "output_01.png"
    )
)

print("✅ Saved")

print(type(result))

if isinstance(result, list):
    print("Length:", len(result))
    print("First element:", type(result[0]))

result[0].save(f"{OUTPUT_DIR}/output_01.png")

from matplotlib import pyplot as plt

plt.imshow(result[0])
plt.axis("off")
plt.show()

print("✅ output_01.png saved")

print(type(result))

if isinstance(result, list):
    print("Length:", len(result))
    print(type(result[0]))

result[0].save(f"{OUTPUT_DIR}/output_01.png")

from matplotlib import pyplot as plt

plt.figure(figsize=(6,8))
plt.imshow(result[0])
plt.axis("off")
plt.show()

print("Saved to:", f"{OUTPUT_DIR}/output_01.png")

print(type(pipeline))
print(hasattr(pipeline, "safety_checker"))

pipeline.safety_checker = None

import inspect

print(inspect.getfile(CatVTONPipeline))

!sed -n '195,220p' /content/CatVTON/model/pipeline.py

pipeline.skip_safety_check = True

result = pipeline(
    image=person,
    condition_image=cloth,
    mask=mask,
    num_inference_steps=30,
    guidance_scale=2.5,
    height=1024,
    width=768,
)

result[0].save(f"{OUTPUT_DIR}/output_01.png")

from PIL import Image
import os

person_files = sorted(os.listdir(PERSON_DIR))
garment_files = sorted(os.listdir(GARMENT_DIR))
mask_files = sorted(os.listdir(MASK_DIR))

for i in range(5):

    print(f"Processing Pair {i+1}/5")

    person = Image.open(
        os.path.join(PERSON_DIR, person_files[i])
    ).convert("RGB")

    cloth = Image.open(
        os.path.join(GARMENT_DIR, garment_files[i])
    ).convert("RGB")

    mask = Image.open(
        os.path.join(MASK_DIR, mask_files[i])
    ).convert("L")

    mask = mask.resize(person.size, Image.NEAREST)

    result = pipeline(
        image=person,
        condition_image=cloth,
        mask=mask,
        num_inference_steps=30,
        guidance_scale=2.5,
        height=1024,
        width=768,
    )

    result[0].save(
        os.path.join(
            OUTPUT_DIR,
            f"output_{i+1:02d}.png"
        )
    )

print("🎉 All 5 outputs generated!")

import matplotlib.pyplot as plt

plt.figure(figsize=(15,5))

plt.subplot(1,3,1)
plt.imshow(person)
plt.title("Person")
plt.axis("off")

plt.subplot(1,3,2)
plt.imshow(mask, cmap="gray")
plt.title("Mask")
plt.axis("off")

plt.subplot(1,3,3)
plt.imshow(cloth)
plt.title("Garment")
plt.axis("off")

plt.show()

print(type(person))
print(type(mask))
print(type(cloth))

print(person.size)
print(mask.size)
print(cloth.size)

mask.save("/content/mask_debug.png")

from matplotlib import pyplot as plt

plt.figure(figsize=(5,8))
plt.imshow(mask, cmap="gray")
plt.axis("off")
plt.show()

import numpy as np

mask_np = np.array(mask)

print(mask_np.shape)
print("Unique values:", np.unique(mask_np))



print(MASK_DIR)

mask.save("/content/mask.png")
person.save("/content/person.png")
cloth.save("/content/cloth.png")

mask.save("/content/mask.png")
person.save("/content/person.png")
cloth.save("/content/cloth.png")

print("Saved!")

from model.cloth_masker import AutoMasker
auto_masker = AutoMasker(
    densepose_ckpt="./checkpoints/CatVTON/DensePose",
    schp_ckpt="./checkpoints/CatVTON/SCHP",
    device=device,
)

print("✅ AutoMasker Loaded")

person = Image.open(
    os.path.join(PERSON_DIR, person_files[0])
).convert("RGB")

mask = auto_masker(
    person,
    mask_type="upper"
)

print(type(mask))

print(type(mask))

if isinstance(mask, dict):
    print(mask.keys())

print(mask)

mask = mask["mask"]

plt.imshow(mask, cmap="gray")
plt.axis("off")
plt.show()

print(type(mask))

import matplotlib.pyplot as plt

plt.figure(figsize=(5,8))
plt.imshow(mask, cmap="gray")
plt.axis("off")
plt.show()

cloth = Image.open(
    os.path.join(GARMENT_DIR, garment_files[0])
).convert("RGB")

result = pipeline(
    image=person,
    condition_image=cloth,
    mask=mask,
    num_inference_steps=30,
    guidance_scale=2.5,
    height=1024,
    width=768,
)

result[0].save(f"{OUTPUT_DIR}/output_01_automask.png")

plt.figure(figsize=(6,8))
plt.imshow(result[0])
plt.axis("off")
plt.show()

import os

output_path = f"{OUTPUT_DIR}/output_01_automask.png"

print("Exists:", os.path.exists(output_path))
print(output_path)



from PIL import Image
import matplotlib.pyplot as plt

img = Image.open(output_path)

plt.figure(figsize=(6,8))
plt.imshow(img)
plt.axis("off")
plt.show()

from PIL import Image
import matplotlib.pyplot as plt

img1 = Image.open(f"{OUTPUT_DIR}/output_01.png")
img2 = Image.open(f"{OUTPUT_DIR}/output_01_automask.png")

plt.figure(figsize=(12,8))

plt.subplot(1,2,1)
plt.imshow(img1)
plt.title("Using Q2 Mask")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(img2)
plt.title("Using AutoMasker")
plt.axis("off")

plt.show()

from PIL import Image
import os

os.makedirs(OUTPUT_DIR, exist_ok=True)

person_files = sorted(os.listdir(PERSON_DIR))
garment_files = sorted(os.listdir(GARMENT_DIR))

for i in range(5):

    print(f"Processing Pair {i+1}/5")

    # Load images
    person = Image.open(
        os.path.join(PERSON_DIR, person_files[i])
    ).convert("RGB")

    cloth = Image.open(
        os.path.join(GARMENT_DIR, garment_files[i])
    ).convert("RGB")

    # Generate CatVTON mask
    mask_dict = auto_masker(
        person,
        mask_type="upper"
    )

    mask = mask_dict["mask"]

    # Run inference
    result = pipeline(
        image=person,
        condition_image=cloth,
        mask=mask,
        num_inference_steps=30,
        guidance_scale=2.5,
        height=1024,
        width=768,
    )

    # Save output
    save_path = os.path.join(
        OUTPUT_DIR,
        f"output_{i+1:02d}.png"
    )

    result[0].save(save_path)

    print("Saved:", save_path)

print("\n🎉 ALL 5 TRY-ON IMAGES GENERATED!")



import os

print(sorted(os.listdir(OUTPUT_DIR)))

import os

extra = os.path.join(OUTPUT_DIR, "output_01_automask.png")

if os.path.exists(extra):
    os.remove(extra)

print(sorted(os.listdir(OUTPUT_DIR)))

readme = """# Q3 - End-to-End Virtual Try-On Inference

## Objective

This notebook performs virtual try-on using the open-source **CatVTON** model. The pipeline generates realistic try-on images for five person-garment pairs by integrating the preprocessing pipeline developed in Q2.

---

## Model

- Model: CatVTON
- Framework: PyTorch + Diffusers
- GPU: Tesla T4 (Google Colab)
- Precision: FP16

---

## Pipeline

1. Load person and garment images.
2. Generate upper-body mask using CatVTON AutoMasker.
3. Perform virtual try-on using CatVTON.
4. Save the generated output image.

---

## Output

The notebook generates:

Q3/
├── outputs/
│   ├── output_01.png
│   ├── output_02.png
│   ├── output_03.png
│   ├── output_04.png
│   └── output_05.png

---

## Constraints Encountered

### 1. Missing Python Dependencies

Errors encountered:
- fvcore
- iopath
- av

Workaround:
Installed the required packages using pip.

---

### 2. Safety Checker

Issue:
The Stable Diffusion safety checker incorrectly classified generated try-on images as NSFW and replaced them with a placeholder image.

Workaround:
Enabled CatVTON's built-in safety bypass using:

pipeline.skip_safety_check = True

---

### 3. Mask Compatibility

Issue:
Using the clothing masks generated in Q2 produced weak garment transfer where only textures/logos were transferred.

Workaround:
Used CatVTON's AutoMasker to generate the upper-body mask expected by the model during inference.

---

### 4. GPU Memory

GPU:
Tesla T4 (Google Colab)

No out-of-memory errors were encountered after using FP16 inference.

---

## Libraries

- torch
- diffusers
- transformers
- accelerate
- peft
- fvcore
- iopath
- av
- Pillow

---

## Author

Nandana R
B.Tech Computer Science (AI)
"""

with open("/content/drive/MyDrive/XIPL_SDE_Assessment/Q3/README.md", "w") as f:
    f.write(readme)

print("✅ README.md created successfully")

PROJECT_DIR = "/content/drive/MyDrive/XIPL_SDE_Assessment"
Q3_DIR = f"{PROJECT_DIR}/Q3"

print(Q3_DIR)

