# -*- coding: utf-8 -*-
"""Q2(new).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmxMWrrMfGzGgwVok43kID_NkLOOB3YZ

# Q2 – Human Parsing and Agnostic Representation
"""

from google.colab import drive
drive.mount('/content/drive')

!nvidia-smi

import torch

print("Torch :", torch.__version__)
print("CUDA  :", torch.cuda.is_available())
print("Device:", torch.cuda.get_device_name(0))

"""## 1. Environment Setup"""

!pip -q install transformers accelerate timm sentencepiece
!pip -q install opencv-python pillow matplotlib tqdm
!pip -q install rembg onnxruntime

"""## 2. Dataset Preparation"""

!mkdir -p /content/drive/MyDrive/XIPL_SDE_Assessment/Q2/dataset

!unzip -q \
"/content/drive/MyDrive/XIPL_SDE_Assessment/Q2/V5.zip" \
-d "/content/drive/MyDrive/XIPL_SDE_Assessment/Q2/dataset"

import os

print(os.listdir("/content/drive/MyDrive"))

import os

for root, dirs, files in os.walk("/content/drive/MyDrive/XIPL_SDE_Assessment"):
    print(root)

import os

DATASET = "/content/drive/MyDrive/XIPL_SDE_Assessment/Q2/dataset"

for root, dirs, files in os.walk(DATASET):
    print(root)

import os

print(os.listdir("/content/drive/MyDrive/XIPL_SDE_Assessment"))

import os

print(os.listdir("/content/drive/MyDrive/XIPL_SDE_Assessment"))

import zipfile

zip_path = "/content/drive/MyDrive/XIPL_SDE_Assessment/V5.zip"
extract_to = "/content/drive/MyDrive/XIPL_SDE_Assessment/Q2/dataset"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_to)

print("✅ Dataset extracted successfully")

!find /content/drive/MyDrive/XIPL_SDE_Assessment/Q2/dataset -maxdepth 3

import os

ROOT = "/content/drive/MyDrive/XIPL_SDE_Assessment/Q2/dataset/sample_files"

PERSON_PATH = os.path.join(ROOT, "test_pairs", "person")
GARMENT_PATH = os.path.join(ROOT, "test_pairs", "garment")
EDGE_PATH = os.path.join(ROOT, "edge_cases")

OUTPUT_ROOT = "/content/drive/MyDrive/XIPL_SDE_Assessment/Q2"

PARSING_PATH = os.path.join(OUTPUT_ROOT, "parsing_maps")
AGNOSTIC_PATH = os.path.join(OUTPUT_ROOT, "agnostic")
GARMENT_MASK_PATH = os.path.join(OUTPUT_ROOT, "garment_masks")
CLOTHING_MASK_PATH = os.path.join(OUTPUT_ROOT, "clothing_masks")

os.makedirs(PARSING_PATH, exist_ok=True)
os.makedirs(AGNOSTIC_PATH, exist_ok=True)
os.makedirs(GARMENT_MASK_PATH, exist_ok=True)
os.makedirs(CLOTHING_MASK_PATH, exist_ok=True)

print("Persons :", os.listdir(PERSON_PATH))
print("Garments:", os.listdir(GARMENT_PATH))
print("Edges   :", os.listdir(EDGE_PATH))

!pip uninstall -y Pillow
!pip install --no-cache-dir --force-reinstall Pillow==10.4.0

import PIL
from PIL import Image, ImageFont

print("Pillow version:", PIL.__version__)

# Simple verification
img = Image.new("RGB", (100, 100), "white")

print("Image module:", Image)
print("ImageFont module:", ImageFont)
print("✅ Pillow working correctly")

import torch
import transformers

from transformers import (
    AutoImageProcessor,
    AutoModelForSemanticSegmentation
)

print("Torch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

print("✅ Q2 imports working")

"""## 3. Load SCHP Model"""

from transformers import AutoImageProcessor, AutoModelForSemanticSegmentation
import torch

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

processor = AutoImageProcessor.from_pretrained(
    "pirocheto/schp-atr-18",
    trust_remote_code=True
)

model = AutoModelForSemanticSegmentation.from_pretrained(
    "pirocheto/schp-atr-18",
    trust_remote_code=True
)

model.to(DEVICE)
model.eval()

print("✅ SCHP Loaded Successfully")
print("Device:", DEVICE)

"""## 4. Generate Parsing Maps"""

from PIL import Image
import matplotlib.pyplot as plt
import os

image_path = os.path.join(PERSON_PATH, "person_01.png")

image = Image.open(image_path).convert("RGB")

plt.figure(figsize=(6,8))
plt.imshow(image)
plt.axis("off")
plt.title("Input Image")
plt.show()

inputs = processor(
    images=image,
    return_tensors="pt"
).to(DEVICE)

with torch.no_grad():
    outputs = model(**inputs)

print(type(outputs))

import numpy as np

parsing_map = outputs.parsing_logits.argmax(dim=1)[0].cpu().numpy()

print("Shape:", parsing_map.shape)
print("Classes:", np.unique(parsing_map))

import matplotlib.pyplot as plt

plt.figure(figsize=(8,8))
plt.imshow(parsing_map, cmap="tab20")
plt.colorbar()
plt.title("SCHP Parsing Map")
plt.axis("off")
plt.show()

import cv2

cv2.imwrite(
    os.path.join(PARSING_PATH, "person_01.png"),
    parsing_map.astype(np.uint8)
)

print("✅ Parsing map saved.")

import torch
import numpy as np

# Get class probabilities
prob = torch.softmax(outputs.parsing_logits[0], dim=0).cpu().numpy()

upper_prob = prob[4]     # Upper clothes
dress_prob = prob[7]     # Dress
belt_prob = prob[8]      # Belt

cloth_mask = (
    (upper_prob > 0.20) |
    (dress_prob > 0.20) |
    (belt_prob > 0.20)
).astype(np.uint8)

print("Mask created.")

import cv2

h, w = cloth_mask.shape

# Only refine the upper torso region
shoulder_region = np.zeros_like(cloth_mask)

shoulder_region[
    int(h*0.08):int(h*0.40),
    :
] = 1

kernel = cv2.getStructuringElement(
    cv2.MORPH_ELLIPSE,
    (5,5)
)

expanded = cv2.dilate(
    cloth_mask,
    kernel,
    iterations=1
)

cloth_mask = np.where(
    shoulder_region == 1,
    expanded,
    cloth_mask
)

kernel = cv2.getStructuringElement(
    cv2.MORPH_ELLIPSE,
    (3,3)
)

cloth_mask = cv2.morphologyEx(
    cloth_mask,
    cv2.MORPH_CLOSE,
    kernel
)

cloth_mask = cv2.resize(
    cloth_mask,
    (image.width, image.height),
    interpolation=cv2.INTER_NEAREST
)

plt.figure(figsize=(6,8))

plt.imshow(
    cloth_mask,
    cmap="gray"
)

plt.title("Refined Clothing Mask")
plt.axis("off")
plt.show()

"""## 5. Create Agnostic Images"""

import numpy as np

# Convert PIL image to NumPy array
image_np = np.array(image)

# Copy original image
agnostic = image_np.copy()

# Replace clothing pixels with gray
agnostic[cloth_mask == 1] = [128, 128, 128]

plt.figure(figsize=(6,8))
plt.imshow(agnostic)
plt.title("Agnostic Image")
plt.axis("off")
plt.show()

from PIL import Image
import os

save_path = os.path.join(
    AGNOSTIC_PATH,
    "person_01.png"
)

Image.fromarray(agnostic).save(save_path)

print("✅ Agnostic image saved to:", save_path)

import os
import cv2
import torch
import numpy as np
from PIL import Image
from tqdm import tqdm

person_files = sorted([
    f for f in os.listdir(PERSON_PATH)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
])

print("Found", len(person_files), "person images")

import os
import cv2
import torch
import numpy as np
from PIL import Image
from tqdm import tqdm

for file_name in tqdm(person_files):

    image_path = os.path.join(PERSON_PATH, file_name)

    image = Image.open(image_path).convert("RGB")

    # ---------------------------
    # SCHP Inference
    # ---------------------------
    inputs = processor(
        images=image,
        return_tensors="pt"
    ).to(DEVICE)

    with torch.no_grad():
        outputs = model(**inputs)

    # ---------------------------
    # Parsing Map
    # ---------------------------
    parsing_map = outputs.parsing_logits.argmax(dim=1)[0].cpu().numpy()

    cv2.imwrite(
        os.path.join(PARSING_PATH, file_name),
        parsing_map.astype(np.uint8)
    )

    # ---------------------------
    # Confidence Mask
    # ---------------------------
    prob = torch.softmax(
        outputs.parsing_logits[0],
        dim=0
    ).cpu().numpy()

    upper = prob[4]
    dress = prob[7]
    belt = prob[8]

    cloth_mask = (
        (upper > 0.20) |
        (dress > 0.20) |
        (belt > 0.20)
    ).astype(np.uint8)

    # ---------------------------
    # Morphology
    # ---------------------------
    kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        (5,5)
    )

    cloth_mask = cv2.morphologyEx(
        cloth_mask,
        cv2.MORPH_CLOSE,
        kernel
    )

    cloth_mask = cv2.resize(
        cloth_mask,
        (image.width, image.height),
        interpolation=cv2.INTER_NEAREST
    )

    # ---------------------------
    # Save Binary Clothing Mask
    # ---------------------------
    Image.fromarray(
        (cloth_mask * 255).astype(np.uint8)
    ).save(
        os.path.join(
            CLOTHING_MASK_PATH,
            file_name
        )
    )

    # ---------------------------
    # Agnostic Image
    # ---------------------------
    image_np = np.array(image)

    agnostic = image_np.copy()

    agnostic[cloth_mask == 1] = [128, 128, 128]

    Image.fromarray(
        agnostic
    ).save(
        os.path.join(
            AGNOSTIC_PATH,
            file_name
        )
    )

print("✅ Batch processing completed.")

import os

print(os.listdir(CLOTHING_MASK_PATH))

from PIL import Image
import matplotlib.pyplot as plt

mask = Image.open(
    "/content/drive/MyDrive/XIPL_SDE_Assessment/Q2/clothing_masks/person_01.png"
)

print(mask.mode)

plt.figure(figsize=(5,5))
plt.imshow(mask, cmap="gray")
plt.axis("off")
plt.show()

print("Parsing Maps:")
print(sorted(os.listdir(PARSING_PATH)))

print("\nAgnostic Images:")
print(sorted(os.listdir(AGNOSTIC_PATH)))

"""## 6. Handle Edge Cases"""

import os

edge_files = sorted([
    f for f in os.listdir(EDGE_PATH)
    if f.lower().endswith((".png", ".jpg", ".jpeg"))
])

print(edge_files)

import os

edge_files = sorted([
    f for f in os.listdir(EDGE_PATH)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
])

print("Edge Files:")
print(edge_files)

import os
import cv2
import torch
import numpy as np
from PIL import Image
from tqdm import tqdm

EDGE_OUTPUT = os.path.join(OUTPUT_ROOT, "edge_cases")

EDGE_PARSING = os.path.join(EDGE_OUTPUT, "parsing_maps")
EDGE_AGNOSTIC = os.path.join(EDGE_OUTPUT, "agnostic")

os.makedirs(EDGE_PARSING, exist_ok=True)
os.makedirs(EDGE_AGNOSTIC, exist_ok=True)

for file_name in tqdm(edge_files):

    # Skip non-image files
    if not file_name.lower().endswith((".jpg", ".jpeg", ".png")):
        continue

    image_path = os.path.join(EDGE_PATH, file_name)

    image = Image.open(image_path).convert("RGB")

    inputs = processor(
        images=image,
        return_tensors="pt"
    ).to(DEVICE)

    with torch.no_grad():
        outputs = model(**inputs)

    parsing_map = outputs.parsing_logits.argmax(dim=1)[0].cpu().numpy()

    unique_classes = np.unique(parsing_map)

    # If only background is predicted, treat it as "no person"
    if len(unique_classes) <= 1:
        print(f"Skipping {file_name} (No person detected)")
        continue

    # Save parsing map
    cv2.imwrite(
        os.path.join(EDGE_PARSING, file_name),
        parsing_map.astype(np.uint8)
    )

    # -----------------------
    # Clothing Mask
    # -----------------------

    prob = torch.softmax(outputs.parsing_logits[0], dim=0).cpu().numpy()

    cloth_mask = (
        (prob[4] > 0.20) |
        (prob[7] > 0.20) |
        (prob[8] > 0.20)
    ).astype(np.uint8)

    kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        (5,5)
    )

    cloth_mask = cv2.morphologyEx(
        cloth_mask,
        cv2.MORPH_CLOSE,
        kernel
    )

    cloth_mask = cv2.resize(
        cloth_mask,
        (image.width, image.height),
        interpolation=cv2.INTER_NEAREST
    )

    image_np = np.array(image)

    agnostic = image_np.copy()

    agnostic[cloth_mask == 1] = [128,128,128]

    Image.fromarray(agnostic).save(
        os.path.join(
            EDGE_AGNOSTIC,
            file_name
        )
    )

    print(f"Processed {file_name}")

print("\n✅ Edge case processing completed.")

print("Parsing Maps:")
print(sorted(os.listdir(EDGE_PARSING)))

print("\nAgnostic Images:")
print(sorted(os.listdir(EDGE_AGNOSTIC)))

"""## 7. Garment Segmentation using rembg"""

!pip -q install rembg onnxruntime

from rembg import remove
from PIL import Image
import matplotlib.pyplot as plt
import os

garment_path = os.path.join(
    GARMENT_PATH,
    "garment_01.jpg"
)

garment = Image.open(garment_path).convert("RGBA")

result = remove(garment)

plt.figure(figsize=(6,6))
plt.imshow(result)
plt.axis("off")
plt.title("Background Removed")
plt.show()

import numpy as np

rgba = np.array(result)

mask = rgba[:,:,3]

plt.figure(figsize=(6,6))
plt.imshow(mask,cmap="gray")
plt.axis("off")
plt.title("Garment Mask")
plt.show()

import cv2

save_path = os.path.join(
    GARMENT_MASK_PATH,
    "garment_01.png"
)

cv2.imwrite(save_path,mask)

print("Saved:",save_path)

"""## 8. Verify Outputs"""

from rembg import remove
from PIL import Image
import numpy as np
import cv2
import os
from tqdm import tqdm

garment_files = sorted([
    f for f in os.listdir(GARMENT_PATH)
    if f.lower().endswith((".jpg",".jpeg",".png"))
])

print(garment_files)

for file in tqdm(garment_files):

    img = Image.open(
        os.path.join(GARMENT_PATH,file)
    ).convert("RGBA")

    result = remove(img)

    rgba = np.array(result)

    mask = rgba[:,:,3]

    out_name = os.path.splitext(file)[0]+".png"

    cv2.imwrite(
        os.path.join(
            GARMENT_MASK_PATH,
            out_name
        ),
        mask
    )

print("\n✅ All garment masks generated.")

print("Parsing Maps :",len(os.listdir(PARSING_PATH)))
print("Agnostic Images :",len(os.listdir(AGNOSTIC_PATH)))
print("Garment Masks :",len(os.listdir(GARMENT_MASK_PATH)))

print("\nGarment Masks")

print(sorted(os.listdir(GARMENT_MASK_PATH)))

from PIL import Image
import matplotlib.pyplot as plt

fig,ax = plt.subplots(1,2,figsize=(10,5))

ax[0].imshow(
    Image.open(
        os.path.join(GARMENT_PATH,"garment_01.jpg")
    )
)

ax[0].set_title("Original")

ax[0].axis("off")

ax[1].imshow(
    Image.open(
        os.path.join(GARMENT_MASK_PATH,"garment_01.png")
    ),
    cmap="gray"
)

ax[1].set_title("Mask")

ax[1].axis("off")

plt.show()

readme = """# Q2 - Human Parsing & Garment Segmentation Pipeline

## Objective

This task prepares person and garment images for a diffusion-based virtual try-on pipeline.

The pipeline performs three main operations:

1. Generate a human parsing map from the person image.
2. Create an agnostic person representation by masking the upper-body clothing region.
3. Segment the garment from its product image and generate a clean garment mask.

---

## Models Used

### Human Parsing - SCHP

Model:
`pirocheto/schp-atr-18`

SCHP is used to generate semantic human parsing information such as clothing and body regions.

The parsing output is then used to identify the upper-body clothing region required for creating the agnostic representation.

### Garment Segmentation - rembg

`rembg` is used to remove the background from garment product images.

The alpha channel of the resulting image is used to create a binary garment mask.

---

## Model Selection and Comparison

| Model | Advantages | Limitations | Decision |
|------|------------|-------------|----------|
| SCHP | Designed specifically for human parsing and provides semantic body/clothing regions | Parsing can be challenging with occlusion and unusual poses | Selected |
| SAM + Grounding DINO | Powerful general-purpose segmentation and text-guided object detection | Requires multiple models and a more complex, computationally expensive pipeline | Not selected |
| DensePose | Provides detailed body-surface and pose information | Does not directly provide the clothing segmentation needed for this task | Not selected |

SCHP was selected because the task specifically requires human parsing and upper-body clothing identification. It provides the semantic information needed to construct the clothing mask while remaining practical to run in Google Colab.

---

## Person Processing Pipeline

The person preprocessing workflow is:

Person Image
    |
    v
SCHP Human Parsing
    |
    v
Parsing Map
    |
    v
Upper-Body Clothing Mask
    |
    v
Mask Refinement
    |
    v
Agnostic Person Representation

The clothing mask is generated from the SCHP probability output for the relevant clothing classes.

A fixed confidence threshold and morphological refinement are applied to obtain a more consistent mask.

The detected upper-body clothing pixels are replaced with a neutral gray region to create the agnostic representation.

---

## Garment Processing Pipeline

The garment preprocessing workflow is:

Garment Product Image
    |
    v
rembg Background Removal
    |
    v
RGBA Garment Image
    |
    v
Extract Alpha Channel
    |
    v
Binary Garment Mask

This separates the garment from the product-image background while retaining its shape.

---

## Edge Case Handling and Testing

The supplied edge cases were explicitly tested through the same processing pipeline.

### Hair Over Shoulders

`person_02` and `person_03` contain hair overlapping the shoulder/clothing region.

These images were processed using the same SCHP human parsing pipeline to evaluate whether clothing regions can still be separated when hair overlaps the upper body.

### Strappy Sleeveless Garment

`garment_03` contains a strappy sleeveless garment.

The garment is processed using rembg so that the garment silhouette, including thin strap regions, can be retained in the garment mask.

### Crossed Arms

`edge_cases/person_crossed_arms.jpg` tests human parsing when the arms overlap the upper-body clothing.

The image is processed using SCHP and both the required parsing map and agnostic representation are generated.

### Side Pose

The supplied side-pose image was additionally passed through the SCHP pipeline to test parsing and clothing-mask robustness under a non-front-facing body orientation.

### Seated Pose

The supplied seated-person image was additionally tested to observe the behavior of the parsing and agnostic-generation pipeline on a seated posture.

### No-Person Image

The supplied no-person image was also tested diagnostically.

SCHP is a human parsing model rather than a dedicated person detector. Therefore, no-person rejection should not rely only on SCHP output. In the complete web-demo pipeline, person validation is handled as a guardrail before try-on processing.

---

## No Filename-Specific Hardcoding

The edge-case outputs are not manually created or hardcoded for individual filenames.

The supplied images are passed through the same SCHP/rembg processing pipeline used for the normal inputs.

The implementation uses fixed processing hyperparameters such as:

- SCHP semantic clothing classes
- Confidence thresholds
- Morphological operations

These are general pipeline parameters and are not manually changed based on a particular test-image filename.

---

## Outputs

The pipeline generates:

### Person Outputs

- Human parsing maps
- Upper-body clothing masks
- Agnostic person representations

### Garment Outputs

- Background-removed garment images
- Binary garment masks

### Edge-Case Outputs

The crossed-arms case includes the required:

- Parsing map
- Agnostic person representation

Additional supplied edge cases were also tested for robustness.

---

## Folder Structure

Q2/
├── person/
├── garment/
├── edge_cases/
├── parsing_maps/
├── agnostic/
├── garment_masks/
├── Q2.ipynb
└── README.md

---

## Libraries Used

- PyTorch
- Transformers
- OpenCV
- NumPy
- Pillow
- rembg
- ONNX Runtime

---

## Implementation Notes

- SCHP performs semantic human parsing.
- Clothing masks are derived from SCHP probability outputs.
- Morphological processing is used to refine clothing-mask regions.
- Agnostic images replace the detected upper-body clothing region with a neutral gray region.
- rembg performs garment background removal.
- Garment masks are extracted from the resulting alpha channel.
- Edge cases are processed through the same general pipeline rather than using manually generated masks.

---

## Author

Nandana R
"""

with open(
    "/content/drive/MyDrive/XIPL_SDE_Assessment/Q2/README.md",
    "w",
    encoding="utf-8"
) as f:
    f.write(readme)

print("✅ Final Q2 README updated successfully!")
print("/content/drive/MyDrive/XIPL_SDE_Assessment/Q2/README.md")

import os

MASK_OUTPUT_DIR = "/content/drive/MyDrive/XIPL_SDE_Assessment/Q2/clothing_masks"

os.makedirs(MASK_OUTPUT_DIR, exist_ok=True)

print("✅ Folder created:", MASK_OUTPUT_DIR)

import os
import numpy as np
import torch
import cv2
import matplotlib.pyplot as plt
from PIL import Image

# ---------------------------------------------------------
# NO-PERSON Q2 DIAGNOSTIC TEST
# ---------------------------------------------------------

no_person_path = os.path.join(
    EDGE_PATH,
    "no_person.jpg"
)

print("Testing:", no_person_path)
print("Exists:", os.path.exists(no_person_path))

# 1. Load image
image = Image.open(no_person_path).convert("RGB")

# 2. Run the SAME SCHP parsing pipeline
inputs = processor(
    images=image,
    return_tensors="pt"
).to(DEVICE)

with torch.no_grad():
    outputs = model(**inputs)

# Parsing prediction
parsing_map = (
    outputs.parsing_logits
    .argmax(dim=1)[0]
    .cpu()
    .numpy()
)

# Probabilities
prob = torch.softmax(
    outputs.parsing_logits,
    dim=1
)[0].cpu().numpy()

# 3. SAME clothing-mask logic used in Q2
cloth_mask = (
    (prob[4] > 0.20) |
    (prob[7] > 0.20) |
    (prob[8] > 0.20)
).astype(np.uint8)

# Same morphology
kernel = cv2.getStructuringElement(
    cv2.MORPH_ELLIPSE,
    (5, 5)
)

cloth_mask = cv2.morphologyEx(
    cloth_mask,
    cv2.MORPH_CLOSE,
    kernel
)

# Resize mask if necessary
image_np = np.array(image)

if cloth_mask.shape != image_np.shape[:2]:
    cloth_mask = cv2.resize(
        cloth_mask,
        (image_np.shape[1], image_np.shape[0]),
        interpolation=cv2.INTER_NEAREST
    )

# 4. Create agnostic representation
agnostic = image_np.copy()

agnostic[cloth_mask == 1] = [
    128,
    128,
    128
]

# ---------------------------------------------------------
# DISPLAY
# ---------------------------------------------------------

plt.figure(figsize=(16, 4))

plt.subplot(1, 4, 1)
plt.imshow(image)
plt.title("Original - No Person")
plt.axis("off")

plt.subplot(1, 4, 2)
plt.imshow(parsing_map)
plt.title("SCHP Parsing Map")
plt.axis("off")

plt.subplot(1, 4, 3)
plt.imshow(cloth_mask, cmap="gray")
plt.title("Upper-Clothing Mask")
plt.axis("off")

plt.subplot(1, 4, 4)
plt.imshow(agnostic)
plt.title("Agnostic Output")
plt.axis("off")

plt.tight_layout()
plt.show()

print("\n===== NO-PERSON DIAGNOSTIC =====")
print("Unique parsing labels:", np.unique(parsing_map))
print("Masked pixels:", int(cloth_mask.sum()))
print(
    "Mask percentage:",
    round(
        100 * cloth_mask.sum() / cloth_mask.size,
        2
    ),
    "%"
)

person_edge_tests = [
    ("person_02.png", os.path.join(PERSON_PATH, "person_02.png"),
     "Hair over shoulders"),

    ("person_03.png", os.path.join(PERSON_PATH, "person_03.png"),
     "Hair over shoulders"),

    ("person_crossed_arms.jpg",
     os.path.join(EDGE_PATH, "person_crossed_arms.jpg"),
     "Crossed arms"),

    ("no_person.jpg",
     os.path.join(EDGE_PATH, "no_person.jpg"),
     "No person")
]

print("===== Q2 PERSON EDGE-CASE TEST =====")

for name, path, case in person_edge_tests:

    print("\n" + "=" * 60)
    print("IMAGE:", name)
    print("EDGE CASE:", case)
    print("EXISTS:", os.path.exists(path))
    print("=" * 60)

    if not os.path.exists(path):
        continue

    image = Image.open(path).convert("RGB")

    # SAME SCHP pipeline
    inputs = processor(
        images=image,
        return_tensors="pt"
    ).to(DEVICE)

    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.parsing_logits

    parsing_map = (
        logits.argmax(dim=1)[0]
        .detach()
        .cpu()
        .numpy()
    )

    prob = torch.softmax(
        logits,
        dim=1
    )[0].detach().cpu().numpy()

    # SAME clothing mask logic
    cloth_mask = (
        (prob[4] > 0.20) |
        (prob[7] > 0.20) |
        (prob[8] > 0.20)
    ).astype(np.uint8)

    kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        (5, 5)
    )

    cloth_mask = cv2.morphologyEx(
        cloth_mask,
        cv2.MORPH_CLOSE,
        kernel
    )

    image_np = np.array(image)

    if cloth_mask.shape != image_np.shape[:2]:
        cloth_mask = cv2.resize(
            cloth_mask,
            (image_np.shape[1], image_np.shape[0]),
            interpolation=cv2.INTER_NEAREST
        )

    agnostic = image_np.copy()

    agnostic[cloth_mask == 1] = [
        128, 128, 128
    ]

    # Display
    plt.figure(figsize=(16, 4))

    plt.subplot(1, 4, 1)
    plt.imshow(image)
    plt.title(name)
    plt.axis("off")

    plt.subplot(1, 4, 2)
    plt.imshow(parsing_map)
    plt.title("SCHP Parsing")
    plt.axis("off")

    plt.subplot(1, 4, 3)
    plt.imshow(cloth_mask, cmap="gray")
    plt.title("Clothing Mask")
    plt.axis("off")

    plt.subplot(1, 4, 4)
    plt.imshow(agnostic)
    plt.title("Agnostic")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

    print(
        "Parsing labels:",
        np.unique(parsing_map)
    )

    print(
        "Mask percentage:",
        round(
            100 * cloth_mask.sum()
            / cloth_mask.size,
            2
        ),
        "%"
    )

import os
import numpy as np
import torch
import cv2
import matplotlib.pyplot as plt
from PIL import Image

test_cases = [
    ("person_seated.jpg",
     os.path.join(EDGE_PATH, "person_seated.jpg")),

    ("person_side_pose.jpg",
     os.path.join(EDGE_PATH, "person_side_pose.jpg"))
]

print("===== Q2 SEATED + SIDE POSE TEST =====")

for filename, path in test_cases:

    print("\n" + "=" * 65)
    print("TESTING:", filename)
    print("Exists:", os.path.exists(path))
    print("=" * 65)

    if not os.path.exists(path):
        print("❌ File not found")
        continue

    # Load image
    image = Image.open(path).convert("RGB")

    # --------------------------------------------------
    # SCHP HUMAN PARSING
    # --------------------------------------------------
    inputs = processor(
        images=image,
        return_tensors="pt"
    ).to(DEVICE)

    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.parsing_logits

    parsing_map = (
        logits.argmax(dim=1)[0]
        .detach()
        .cpu()
        .numpy()
    )

    # --------------------------------------------------
    # PROBABILITY MAP
    # --------------------------------------------------
    prob = torch.softmax(
        logits,
        dim=1
    )[0].detach().cpu().numpy()

    # SAME clothing-mask logic used in Q2
    cloth_mask = (
        (prob[4] > 0.20) |
        (prob[7] > 0.20) |
        (prob[8] > 0.20)
    ).astype(np.uint8)

    # --------------------------------------------------
    # MORPHOLOGY
    # --------------------------------------------------
    kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        (5, 5)
    )

    cloth_mask = cv2.morphologyEx(
        cloth_mask,
        cv2.MORPH_CLOSE,
        kernel
    )

    # --------------------------------------------------
    # CREATE AGNOSTIC IMAGE
    # --------------------------------------------------
    image_np = np.array(image)

    if cloth_mask.shape != image_np.shape[:2]:
        cloth_mask = cv2.resize(
            cloth_mask,
            (image_np.shape[1], image_np.shape[0]),
            interpolation=cv2.INTER_NEAREST
        )

    agnostic = image_np.copy()

    agnostic[cloth_mask == 1] = [
        128,
        128,
        128
    ]

    # --------------------------------------------------
    # DISPLAY RESULTS
    # --------------------------------------------------
    plt.figure(figsize=(16, 4))

    plt.subplot(1, 4, 1)
    plt.imshow(image)
    plt.title(f"Original\n{filename}")
    plt.axis("off")

    plt.subplot(1, 4, 2)
    plt.imshow(parsing_map)
    plt.title("SCHP Parsing Map")
    plt.axis("off")

    plt.subplot(1, 4, 3)
    plt.imshow(cloth_mask, cmap="gray")
    plt.title("Upper Clothing Mask")
    plt.axis("off")

    plt.subplot(1, 4, 4)
    plt.imshow(agnostic)
    plt.title("Agnostic Image")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

    # --------------------------------------------------
    # DIAGNOSTIC INFORMATION
    # --------------------------------------------------
    print(
        "Unique parsing labels:",
        np.unique(parsing_map)
    )

    print(
        "Masked pixels:",
        int(cloth_mask.sum())
    )

    print(
        "Mask percentage:",
        round(
            100 * cloth_mask.sum()
            / cloth_mask.size,
            2
        ),
        "%"
    )

print("\n✅ SEATED + SIDE POSE TEST COMPLETED")